development:
  adapter: postgresql
  #url: postgres://localhost/pg_notify_poc

test:
  adapter: async

production:
  adapter: postgresql
  #url: <%= ENV['DATABASE_URL'] %>
  #channel_prefix: pg-notify-poc_production
